"""schema_revisions

Revision ID: fd8970c8bf8f
Revises: 
Create Date: 2026-08-10 19:24:25.475390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'fd8970c8bf8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS eventstatus CASCADE;")
    op.execute("DROP TYPE IF EXISTS obstructionstatus CASCADE;")
    op.execute("DROP TYPE IF EXISTS operationalstatus CASCADE;")
    
    operationalstatus = postgresql.ENUM('LAYAK', 'RUSAK_RINGAN', 'RUSAK_BERAT', 'TIDAK_LAYAK', name='operationalstatus')
    operationalstatus.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='eventstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_events_external_event_id'), 'emergency_events', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_emergency_events_id'), 'emergency_events', ['id'], unique=False)
    op.create_table('obstructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('edge_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CROWD_CONFIRMED', 'OFFICIAL_CONFIRMED', 'REJECTED', 'EXPIRED', name='obstructionstatus'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obstructions_edge_id'), 'obstructions', ['edge_id'], unique=False)
    op.create_index(op.f('ix_obstructions_event_id'), 'obstructions', ['event_id'], unique=False)
    op.create_index(op.f('ix_obstructions_id'), 'obstructions', ['id'], unique=False)
    op.add_column('checkins', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('checkins', sa.Column('device_hash', sa.String(), nullable=False))
    op.add_column('checkins', sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('checkins', 'evacuation_point_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.drop_index(op.f('ix_checkins_device_id'), table_name='checkins')
    op.create_index(op.f('ix_checkins_device_hash'), 'checkins', ['device_hash'], unique=False)
    op.create_index(op.f('ix_checkins_event_id'), 'checkins', ['event_id'], unique=False)
    op.create_unique_constraint('uq_event_device', 'checkins', ['event_id', 'device_hash'])
    op.create_foreign_key('fk_checkins_emergency_events', 'checkins', 'emergency_events', ['event_id'], ['id'])
    op.drop_column('checkins', 'created_at')
    op.drop_column('checkins', 'device_id')
    op.add_column('data_versions', sa.Column('schema_version', sa.String(), nullable=True))
    op.add_column('data_versions', sa.Column('download_url', sa.String(), nullable=True))
    op.add_column('data_versions', sa.Column('size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('data_versions', sa.Column('minimum_app_version', sa.String(), nullable=True))
    op.add_column('data_versions', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('data_versions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_dataset_version', 'data_versions', ['dataset_name', 'version'])
    op.add_column('evacuation_points', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('evacuation_points', sa.Column('operational_status', sa.Enum('LAYAK', 'RUSAK_RINGAN', 'RUSAK_BERAT', 'TIDAK_LAYAK', name='operationalstatus'), nullable=True))
    op.add_column('evacuation_points', sa.Column('source', sa.String(), nullable=True))
    op.add_column('evacuation_points', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('evacuation_points', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('evacuation_points', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_evacuation_points_external_id'), 'evacuation_points', ['external_id'], unique=True)
    op.drop_constraint(op.f('evacuation_points_inundation_zone_id_fkey'), 'evacuation_points', type_='foreignkey')
    op.drop_constraint(op.f('evacuation_points_safe_zone_id_fkey'), 'evacuation_points', type_='foreignkey')
    op.drop_column('evacuation_points', 'is_operational')
    op.drop_column('evacuation_points', 'inundation_zone_id')
    op.drop_column('evacuation_points', 'safe_zone_id')
    op.alter_column('inundation_zones', 'geometry',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.add_column('obstruction_reports', sa.Column('obstruction_id', sa.Integer(), nullable=False))
    op.add_column('obstruction_reports', sa.Column('device_hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_obstruction_reports_device_id'), table_name='obstruction_reports')
    op.create_index(op.f('ix_obstruction_reports_device_hash'), 'obstruction_reports', ['device_hash'], unique=False)
    op.create_index(op.f('ix_obstruction_reports_obstruction_id'), 'obstruction_reports', ['obstruction_id'], unique=False)
    op.create_foreign_key('fk_obstruction_reports_obstructions', 'obstruction_reports', 'obstructions', ['obstruction_id'], ['id'])
    op.drop_column('obstruction_reports', 'is_verified')
    op.drop_column('obstruction_reports', 'edge_id')
    op.drop_column('obstruction_reports', 'expires_at')
    op.drop_column('obstruction_reports', 'device_id')
    op.alter_column('safe_zones', 'geometry',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('safe_zones', 'geometry',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    op.add_column('obstruction_reports', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('obstruction_reports', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('obstruction_reports', sa.Column('edge_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('obstruction_reports', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_obstruction_reports_obstructions', 'obstruction_reports', type_='foreignkey')
    op.drop_index(op.f('ix_obstruction_reports_obstruction_id'), table_name='obstruction_reports')
    op.drop_index(op.f('ix_obstruction_reports_device_hash'), table_name='obstruction_reports')
    op.create_index(op.f('ix_obstruction_reports_device_id'), 'obstruction_reports', ['device_id'], unique=False)
    op.drop_column('obstruction_reports', 'device_hash')
    op.drop_column('obstruction_reports', 'obstruction_id')
    op.alter_column('inundation_zones', 'geometry',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    op.add_column('evacuation_points', sa.Column('safe_zone_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('evacuation_points', sa.Column('inundation_zone_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('evacuation_points', sa.Column('is_operational', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('evacuation_points_safe_zone_id_fkey'), 'evacuation_points', 'safe_zones', ['safe_zone_id'], ['id'])
    op.create_foreign_key(op.f('evacuation_points_inundation_zone_id_fkey'), 'evacuation_points', 'inundation_zones', ['inundation_zone_id'], ['id'])
    op.drop_index(op.f('ix_evacuation_points_external_id'), table_name='evacuation_points')
    op.alter_column('evacuation_points', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('evacuation_points', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('evacuation_points', 'updated_at')
    op.drop_column('evacuation_points', 'source')
    op.drop_column('evacuation_points', 'operational_status')
    op.drop_column('evacuation_points', 'external_id')
    op.drop_constraint('uq_dataset_version', 'data_versions', type_='unique')
    op.drop_column('data_versions', 'is_active')
    op.drop_column('data_versions', 'published_at')
    op.drop_column('data_versions', 'minimum_app_version')
    op.drop_column('data_versions', 'size_bytes')
    op.drop_column('data_versions', 'download_url')
    op.drop_column('data_versions', 'schema_version')
    op.add_column('checkins', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('checkins', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint('fk_checkins_emergency_events', 'checkins', type_='foreignkey')
    op.drop_constraint('uq_event_device', 'checkins', type_='unique')
    op.drop_index(op.f('ix_checkins_event_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_device_hash'), table_name='checkins')
    op.create_index(op.f('ix_checkins_device_id'), 'checkins', ['device_id'], unique=False)
    op.alter_column('checkins', 'evacuation_point_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('checkins', 'checked_in_at')
    op.drop_column('checkins', 'device_hash')
    op.drop_column('checkins', 'event_id')
    op.drop_index(op.f('ix_obstructions_id'), table_name='obstructions')
    op.drop_index(op.f('ix_obstructions_event_id'), table_name='obstructions')
    op.drop_index(op.f('ix_obstructions_edge_id'), table_name='obstructions')
    op.drop_table('obstructions')
    op.drop_index(op.f('ix_emergency_events_id'), table_name='emergency_events')
    op.drop_index(op.f('ix_emergency_events_external_event_id'), table_name='emergency_events')
    op.drop_table('emergency_events')
    
    eventstatus = postgresql.ENUM('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='eventstatus')
    eventstatus.drop(op.get_bind(), checkfirst=True)
    
    obstructionstatus = postgresql.ENUM('PENDING', 'CROWD_CONFIRMED', 'OFFICIAL_CONFIRMED', 'REJECTED', 'EXPIRED', name='obstructionstatus')
    obstructionstatus.drop(op.get_bind(), checkfirst=True)

    operationalstatus = postgresql.ENUM('LAYAK', 'RUSAK_RINGAN', 'RUSAK_BERAT', 'TIDAK_LAYAK', name='operationalstatus')
    operationalstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
