"""event_administration

Revision ID: baeb39a435c6
Revises: d3354ac33c10
Create Date: 2026-09-19 16:11:00.977805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeb39a435c6'
down_revision: Union[str, Sequence[str], None] = 'd3354ac33c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    sa_enum = postgresql.ENUM('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='eventstatus', create_type=False)
    
    op.create_table('event_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa_enum, nullable=True),
    sa.Column('new_status', sa_enum, nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_status_history_event_id'), 'event_status_history', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_status_history_id'), 'event_status_history', ['id'], unique=False)
    op.add_column('emergency_events', sa.Column('is_simulation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    # Data Migration untuk event testing lama
    op.execute("UPDATE emergency_events SET is_simulation = true WHERE external_event_id = 'EVENT-PADANG-TEST-01'")
    
    op.drop_index(op.f('uq_single_active_tsunami_event'), table_name='emergency_events', postgresql_where="(status = 'ACTIVE'::eventstatus)")
    op.create_index('uq_single_active_tsunami_event', 'emergency_events', ['status', 'is_simulation'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_single_active_tsunami_event', table_name='emergency_events', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('uq_single_active_tsunami_event'), 'emergency_events', ['status'], unique=True, postgresql_where="(status = 'ACTIVE'::eventstatus)")
    op.drop_column('emergency_events', 'is_simulation')
    op.drop_index(op.f('ix_event_status_history_id'), table_name='event_status_history')
    op.drop_index(op.f('ix_event_status_history_event_id'), table_name='event_status_history')
    op.drop_table('event_status_history')
    # ### end Alembic commands ###
